# Generated by Django 3.0.6 on 2020-07-04 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='image',
        ),
    ]
