# Generated by Django 3.0.6 on 2020-07-04 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0004_auto_20200704_2134'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='all_product',
            new_name='product',
        ),
    ]
