# Generated by Django 3.0.6 on 2020-07-11 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0009_auto_20200705_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
    ]
