# Generated by Django 3.0.6 on 2020-07-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0012_auto_20200728_2251'),
    ]

    operations = [
        migrations.DeleteModel(
            name='article',
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.CharField(max_length=130),
        ),
    ]
