# Generated by Django 3.0.6 on 2020-07-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0013_auto_20200728_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('categories', models.CharField(default='', max_length=60)),
                ('slug', models.SlugField(max_length=130)),
                ('date', models.DateField()),
            ],
        ),
    ]
